### ISSUE TITLE
Runtime issue: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by mattjackson1** [dequelabs/axe-core#1259]
<< Please describe how you encountered this issue >>

```
TypeError: Cannot read property '0' of undefined
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:109:137989
    at Array.every (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:109:137957
    at Array.forEach (<anonymous>)
    at Object.a.filteredRectStack (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:109:137901)
    at Object.a.getBackgroundStack (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:109:138215)
    at Object.a.getBackgroundColor (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:109:139420)
    at Object.evaluate (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:109:68263)
    at b.run (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:76:8610)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:76:12663
```

**Comment by marcysutton** [comment]
Hi @mattjackson1, we need more details to debug this issue. Can you provide a Codepen or working demo that we can use to reproduce this issue? Otherwise it will be closed.

**Comment by stephenmathieson** [comment]
This looks like a duplicate of https://github.com/dequelabs/axe-core/issues/1306
