### ISSUE TITLE
Runtime issue: TypeError: Cannot read property 'nodeName' of undefined

### ISSUE THREAD

**Issue by rosibaj** [dequelabs/axe-core#1266]
We ran axe on https://portal.gdc.cancer.gov/files/bdfeb593-3919-4e8d-9d03-cf613de35aaa

This looks like an error with the extension, not the page as far as we can tell

```
TypeError: Cannot read property 'nodeName' of undefined
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:109:149458
    at Array.reduce (<anonymous>)
    at Object.l.getScope (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:109:149418)
    at Object.l.isColumnHeader (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:109:149565)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:109:94883
    at Array.reduce (<anonymous>)
    at Object.evaluate (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:109:94748)
    at b.run (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:76:8610)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:76:12663
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:109:3865
```

**Comment by marcysutton** [comment]
The check in question is `th-has-data-cells`. I can't tell exactly where this is in the source due to minification but there are a few `array.reduce` calls with `nodeName` in `axe.commons.table.getScope` and `axe.commons.table.hasContent`. It could be thrown by either of those for some reason...maybe it's iterating over DOM nodes and not virtual nodes?
