### ISSUE TITLE
Runtime issue: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1306]
I got the following error running axe on https://www.luckyscript.me/

```
TypeError: Cannot read property '0' of undefined
    at chrome-extension://lfmcehohgifnaodaogknapedjiaoebgo/adapter.bundle.js:68:165689
    at Array.every (<anonymous>)
    at chrome-extension://lfmcehohgifnaodaogknapedjiaoebgo/adapter.bundle.js:68:165657
    at Array.forEach (<anonymous>)
    at Object.i.filteredRectStack (chrome-extension://lfmcehohgifnaodaogknapedjiaoebgo/adapter.bundle.js:68:165601)
    at Object.i.getBackgroundStack (chrome-extension://lfmcehohgifnaodaogknapedjiaoebgo/adapter.bundle.js:68:165915)
    at Object.i.getBackgroundColor (chrome-extension://lfmcehohgifnaodaogknapedjiaoebgo/adapter.bundle.js:68:167120)
    at Object.evaluate (chrome-extension://lfmcehohgifnaodaogknapedjiaoebgo/adapter.bundle.js:68:96067)
    at v.run (chrome-extension://lfmcehohgifnaodaogknapedjiaoebgo/adapter.bundle.js:37:8511)
    at chrome-extension://lfmcehohgifnaodaogknapedjiaoebgo/adapter.bundle.js:37:12495
```

**Comment by stephenmathieson** [comment]
Is this a bug with axe-core itself, or a problem in the extension? Looking at the provided stacktrace, it looks like it's coming from the extension.

**Comment by stephenmathieson** [comment]
This is a bug in axe-core itself. Sometimes [one of these `rects`](https://github.com/dequelabs/axe-core/blob/v3.1.2/lib/commons/color/get-background-color.js#L284-L285) are `undefined`.

I haven't figured out why yet.

**Comment by stephenmathieson** [comment]
Reopening this to remind us to look into the root cause of this problem.
