### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by patrickhulce** [dequelabs/axe-core#1397]
Run axe on https://www.homeyou.com/

Actual: Fails immediately with 
```
TypeError: Cannot read property 'indexOf' of undefined
    at te (chrome-extension://<id>/adapter.bundle.js:76:59210)
    at Array.filter (<anonymous>)
    at a (chrome-extension://<id>/adapter.bundle.js:76:61464)
    at Object.H.utils.getSelectorData (chrome-extension://<id>/adapter.bundle.js:76:61665)
    at Object.q [as _runRules] (chrome-extension://<id>/adapter.bundle.js:76:35171)
    at Object.H.run (chrome-extension://<id>/adapter.bundle.js:76:37333)
    at Object.analyze (chrome-extension://<id>/adapter.bundle.js:99:285715)
    at chrome-extension://<id>/adapter.bundle.js:99:284178
    at onMessage (chrome-extension://<id>/browser-polyfill.js:1056:22)
```

Expectation: Run completes without error

Motivation: https://github.com/GoogleChrome/lighthouse/issues/7355

<pre><code>
axe-core version: 3.1.2
axe-webdriver, extension or other integration version: 3.7.0

Browser and Assistive Technology versions
Chrome 72.0.3626.119
</code></pre>

**Comment by WilcoFiers** [comment]
Howdy! Thank you. I've been aware this existed for a while now but never found a place to reproduce it. We'll be sure to have a look.

**Comment by straker** [comment]
So the issue is caused by one of the form elements on the page clobbering the DOM and overriding `node.attributes`. 

```html
<form>
   <select name="attributes">
</form
```

This causes `node.attributes` to return the `<select>` element instead of a `NamedNodeMap`. To fix this we just have to check that `node.attributes` is an instanceof `NamedNodeMap` before we loop over it.
