### ISSUE TITLE
Fix the axeFunction to support all use cases including Java TestNG

### ISSUE THREAD

**Issue by scottizu** [dequelabs/axe-core#1510]
We have two rule sets we run:

1. wa11y
(eBay's ruleset written in 2014)
2. aXe (Deque's ruleset)

We run accessibility testing many different ways:

1. Java Test NG wrapper for ruleset javascript files
2. Copy and paste ruleset javascript files into Chrome Browser console and then execute various commands to run
3. aXe Chrome Extension (uses aXe)
4. eBay's Go Quickly Chrome Extension (uses aXe and wa11y)
5. Python
6. Node
7. Node Mocha Chai ChromeDriver

For running in Java Test NG wrapper we execute with this

```
((JavascriptExecutor) this.driver).executeScript(aXe);
...
command = String.format("axe.a11yCheck(document, %s, arguments[arguments.length - 1]);", options);
Object response = ((JavascriptExecutor) this.driver).executeAsyncScript(command);
```

Here is the error
```
org.openqa.selenium.WebDriverException: unknown error: "id" is required
  (Session info: chrome=73.0.3683.103)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.16299 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 150 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'D-SJC-11014393', ip: '10.254.37.102', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab), userDataDir=C:\Users\sizu\AppData\Local\Temp\scoped_dir163968_30182}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=73.0.3683.103, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=false, acceptInsecureCerts=false, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]
Session ID: 006f22646ecf7e7f0b852eb9b3d6ac16
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:573)
	at com.ebay.qi.wae.core.AXE.inject(AXE.java:75)
	at com.ebay.qi.wae.core.WAEEngine.runAccessibilityRulesPostProcessing(WAEEngine.java:262)
	at com.ebay.qi.wae.core.WAEEngine.runAccessibilityRules(WAEEngine.java:64)
	at com.ebay.qi.wae.listener.WAEController.runAccessibilityRules(WAEController.java:96)
	at com.ebay.qi.wae.listener.WAEController.runAllAccessibilityRulesForPage(WAEController.java:92)
	at com.ebay.qi.wae.test.demo.RunDevComplete.completeRunTest(RunDevComplete.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
```

to get around this, we must comment out these lines in axeFunction
```
// if (typeof define === 'function' && define.amd) {
//    define('axe-core', [], function() {
//      'use strict';
//      return axe;
//    });
//  }
```

**Comment by WilcoFiers** [comment]
@scottizu do you have any theories of what Java TestNG might be doing that's causing these issues? The module definition is part of standard workings of axe-core, so we can't remove it. We also don't have any official integrations for TestNG.

I don't think there is much we can do about this. If you have a fix you'd like to propose, I'd be happy to consider it, provided it doesn't break existing functionality. If you have a need for additional support, Deque provides support agreements for axe-core, as well as having an enterprise service called WorldSpace Attest, which is build on top of our open source work.

**Comment by dylanb** [comment]
@WilcoFiers we could generate a different target for use in TestNG

**Comment by WilcoFiers** [comment]
Closing the issue, since we got no response on it. @scottizu, if you'd like to propose a change, please put together a pull request or a new issue.
