### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by bobbyaccessibilitystuff** [dequelabs/axe-core#1554]
I can't test any pages, keep getting this error:
TypeError: Cannot read property 'nodeMap' of undefined
    at G (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:97:74309)
    at Object.utils.getFlattenedTree (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:97:81423)
    at Object.j [as cleanup] (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:97:51377)
    at chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:109:321777
    at new Promise (<anonymous>)
    at Object.u [as highlight] (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:109:321749)
    at chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:85:171163
    at onMessage (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/browser-polyfill.js:1056:22)

Expectation: Testing works

Actual: Error Message when runing audit: An error occured (see above message)

Motivation: N/A

<pre><code>
axe-core version: v3.8.0
axe-webdriver, extension or other integration version: axe-core 3.2.2-canary.b573b1c

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  Mac/Chrome
</code></pre>

**Comment by straker** [comment]
Thanks for reporting the issue. Unfortunately axe-coconut is currently broken and a fix is underway. Please follow along with #1532 for additional updates.
