### ISSUE TITLE
Tests fail when trying to run on remote browsers.

### ISSUE THREAD

**Issue by sirishav** [dequelabs/axe-core#2082]
Expectation: Should be able to run the tests on remote browsers. We use a cross browser testing tool called Lambdatest(browsers on cloud server) and we want to configure the tests integrated with axe to be run on the tool. 
Actual: The tests fail with below error
**org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.**
      Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
      System info: host: 'IS-2314s-MacBook-Pro.local', ip: 'fe80:0:0:0:479:457d:6cdf:4014%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_131'
      Driver info: driver.version: RemoteWebDriver
      Capabilities [{moz:profile=C:\Users\ltuser\AppData\Local\Temp\rust_mozprofilei96m8I, rotatable=false, moz:geckodriverVersion=0.26.0, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss and notify, strictFileInteractability=false, moz:headless=false, platform=ANY, moz:accessibilityChecks=false, moz:useNonSpecCompliantPointerOrigin=false, webdriver.remote.sessionid=a4c0eb44-6f3d-42e6-81bc-a9db8dcdb869, acceptInsecureCerts=true, browserVersion=74.0, moz:shutdownTimeout=60000.0, platformVersion=10.0, moz:processID=1120.0, browserName=firefox, moz:buildID=20200210140608, javascriptEnabled=true, platformName=windows, setWindowRect=true, moz:webdriverClick=true}]
      Session ID: a4c0eb44-6f3d-42e6-81bc-a9db8dcdb869
      	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
      	at org.openqa.selenium.remote.RemoteWebDriver.executeAsyncScript(RemoteWebDriver.java:591)
      	at com.deque.axe.AXE$Builder.execute(AXE.java:372)
      	at com.deque.axe.AXE$Builder.analyze(AXE.java:335)
      	at com.scholastic.word.utility.AxeAccessibilityUtilities.testAccessibility(AxeAccessibilityUtilities.java:34)
      	at com.scholastic.word.stepdefinitions.AxeAccessibilityStepDefs.i_want_to_check_the_violations_on_the_overview_page(AxeAccessibilityStepDefs.java:12)
      	at ✽.And I want to check the violations on the overview page(AxeAccessibilityTests.feature:8)
      **Caused by: javax.net.ssl.SSLException: SSL peer shut down incorrectly**
      	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:596)
      	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
      	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
      	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
      	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
      	at org.apache.http.impl.conn.LoggingInputStream.read(LoggingInputStream.java:84)
      	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
      	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:198)
      	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
      	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
      	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:148)
      	at org.apache.http.util.EntityUtils.toByteArray(EntityUtils.java:136)

**Comment by AdnoC** [comment]
Hi @sirishav, does this error happen consistenly or just sometimes? Can you post a snippet that we can use to reproduce the error?

**Comment by straker** [comment]
Closing as without more details we cannot do anything about this. Please feel free to reopen with more details.
