### ISSUE TITLE
axe chrome extension initial connection error, then working

### ISSUE THREAD

**Issue by tillypick** [dequelabs/axe-core#2084]
I am a first time user of axe and am submitting this in case it is helpful to you. As you'll see at the end of this entry, axe looks like it's working correctly now. My expectation was for axe to function correctly, which it initially did not.

I first added the chrome axe extension, then went to www.veritasgenetics.com, right-clicked for developer tools, scrolled right to the axe tab, clicked "analyze" to check the page, and got the following error message and details.

**Error: Could not establish connection. Receiving end does not exist.**
TypeError: Cannot read property 'documentElement' of null
TypeError: 
    at e (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:187155)
    at Object.utils.getFlattenedTree (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:187966)
    at U (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:165293)
    at G (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:166349)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:218845
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:218863
    at l (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:218367)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:218570

To troubleshoot, I then tried it on https://www.veritasgenetics.com/myGenome and got the following error details

TypeError: Cannot read property 'documentElement' of null
    at e (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:187155)
    at Object.utils.getFlattenedTree (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:187966)
    at Object.U [as cleanup] (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:165293)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:1:250613
    at new Promise (<anonymous>)
    at Object.r [as highlight] (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:1:250585)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:1:244052
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/browser-polyfill.js:1:9539

When I then went back to the home page, getting the same error again, and then returned to https://www.veritasgenetics.com/myGenome, it seemed to work fine.

**Comment by straker** [comment]
Thanks for letting us know. We'll take a look to see if we can figure out what's going on.

**Comment by jmcunningham** [comment]
The same error happened to me in Chrome (Mac OS). I installed the Axe Web Chrome plugin, opened DevTools and tried to Analyze my current page (running on localhost). I got the same connection error.

To fix it, I just refreshed the page I was trying to test. It appears that you need to reload the page under test, after the plugin is installed.

**Comment by erik-deque** [comment]
This happens when you have a page loaded before adding the extension (most often use case). We are currently adding helpful tips that will be released in the next version.

**Comment by erik-deque** [comment]
We've added more information around this error and how to resolve in 4.7.1
