### ISSUE TITLE
TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by Cerberooo** [dequelabs/axe-core#2173]
Error:

```
(node:20890) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Right-hand side of 'instanceof' is not callable
    at getRootNode (…/node_modules/axe-core/axe.js:9032:16)
    at new Context (…/node_modules/axe-core/axe.js:9045:48)
    at Object.runRules [as _runRules] (…/node_modules/axe-core/axe.js:10155:17)
    at Object.axe.run (…/node_modules/axe-core/axe.js:10354:9)
    at runAxe (__puppeteer_evaluation_script__:11:23)
    at ExecutionContext._evaluateInternal (…/node_modules/puppeteer/lib/ExecutionContext.js:115:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (…/node_modules/puppeteer/lib/ExecutionContext.js:43:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (…/node_modules/puppeteer/lib/helper.js:105:23)
    at DOMWorld.evaluate (…/node_modules/puppeteer/lib/DOMWorld.js:102:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (…/node_modules/puppeteer/lib/helper.js:105:23)
    at AxePuppeteer.<anonymous> (…/node_modules/axe-puppeteer/src/axePuppeteer.ts:227:43)
    at Generator.next (<anonymous>)
    at fulfilled (…/node_modules/axe-puppeteer/dist/axePuppeteer.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I'm crawling webpages with puppeteer and searching for accessibility errors. 

<pre><code>
axe-core version: 3.5.3
axe-puppeteer: 1.1.0
puppeteer: 3.0.0
node: 13.13.0
linux: 5.6.5-arch3-1
</code></pre>

**Comment by Cerberooo** [comment]
It was a redirect / puppeteer issue.
