### ISSUE TITLE
Runtime issue: TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by ruchiaa** [dequelabs/axe-core#2285]
Running "Analyze" on a page using the chrome extension. The page has a mat-table that has some empty cells. When I populate the table, the issue goes away.

```
TypeError: Cannot read property 'filter' of undefined
    at T (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:431539)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:432507
    at Array.map (<anonymous>)
    at Object.i.getTextElementStack (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:432484)
    at Object.a.getRectStack (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:424075)
    at Object.a.filteredRectStack (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:423624)
    at Object.a.getBackgroundStack (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:423027)
    at Object.a.getBackgroundColor (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:422529)
    at Object.evaluate (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:344613)
    at k.run (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:152463)
```

**Comment by straker** [comment]
Thanks for the issue. Are you able to provide the site where the error occurs so I can try to reproduce it?

**Comment by straker** [comment]
@ruchiaa any update on this?

**Comment by padmavemulapati** [comment]
Verified with axe-core3.5.5 , not seeing any error , and results showing in passes (notin incomplete like earlier)
![image](https://user-images.githubusercontent.com/47409579/85301501-8750d500-b4c5-11ea-8c1f-486b964c86f0.png)
