### ISSUE TITLE
Runtime issue: TypeError: Cannot read property '3' of undefined

### ISSUE THREAD

**Issue by paulweight** [dequelabs/axe-core#2482]
<< Please describe how you encountered this issue >>

```
TypeError: Cannot read property '3' of undefined
    at T (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:432081)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:433053
    at Array.map (<anonymous>)
    at Object.i.getTextElementStack (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:433030)
    at Object.a.getRectStack (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:424621)
    at Object.a.filteredRectStack (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:424170)
    at Object.a.getBackgroundStack (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:423573)
    at Object.a.getBackgroundColor (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:423075)
    at Object.evaluate (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:345078)
    at k.run (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:152463)
```

**Comment by straker** [comment]
Could you provide a with a link to the website that throws the error or a code snippet that reproduces it? Without that I'm unable to figure out what's going on and try to fix it.

**Comment by straker** [comment]
Closing as without more details we cannot do anything about this. Please feel free to reopen with more details.
