### ISSUE TITLE
Runtime issue: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by adriangiurca** [dequelabs/axe-core#2602]
After upgrading to axe-core 4.0.2 I am receiving the following error when I analyze the page.
I mention that on previous axe versions this issue was not displayed.

<img width="386" alt="axe error" src="https://user-images.githubusercontent.com/44003757/97411956-93ccba80-1909-11eb-81f0-e432217a71bf.png">

```
RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at t.default (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:33:174491)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:33:159317
    at Array.reduce (<anonymous>)
    at p (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:33:159251)
    at t.default (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:33:160146)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:33:51593
    at Array.reduce (<anonymous>)
    at t.default (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:33:51548)
    at g (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:33:148134)
```

**Comment by WilcoFiers** [comment]
Hey @adriangiurca, can you share some information on how to reproduce the issue?

**Comment by WilcoFiers** [comment]
Closing due to inactivity. If you do have this info, feel free to reopen.
