### ISSUE TITLE
Runtime issue: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by patrickhulce** [dequelabs/axe-core#2681]
Originally filed at https://github.com/GoogleChrome/lighthouse/issues/11721#issuecomment-740267214

Run axe on https://www.rome2rio.com/s/Mumbai/Delhi

Supposedly related an interaction with color-contrast and `overflow: scroll`? From that original Lighthouse issue...

> I notice if I remove a overflow-x: scroll style attribute from two sections (Things to do, Places to stay) then the error goes away

```
TypeError: Cannot read property '0' of undefined
    at g (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:33:117582)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:33:119639
    at Array.map (<anonymous>)
    at t.default (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:33:119593)
    at t.default (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:33:105942)
    at t.default (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:33:101530)
    at t.default (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:33:103754)
    at t.default (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:33:102856)
    at Object.t.default (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:33:15179)
    at c.run (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:33:187710)
```

**Comment by straker** [comment]
Thanks for the issue. It is indeed a separate problem and we'll be sure to get it fixed.

**Comment by padmavemulapati** [comment]
@straker , is it similar to "axe-core Error: Cannot read property 'filter' of undefined" #2483 ?

**Comment by straker** [comment]
@padmavemulapati kinda of. They throw an error in the same place / way, but the causes are different.

**Comment by padmavemulapati** [comment]
Verified with the latest axe-core-develop codebase - 
Working fine with handling of text that overflows outside the parent:
TestScript:
`<div id="1" style="width: 250px; overflow: hidden">`
   ` <p id="target" style="max-height: 80px; overflow: hidden; line-height: 20px; font-size: 13px;">The Chandni Chowk (Moonlight Square) is one of the oldest and busiest markets in Old Delhi, India. Chandni Chowk is located close to Old Delhi Railway Station. The Red Fort monument is located within the market. It was built in the 17th century by Mughal Emperor of India Shah Jahan and designed by his daughter Jahanara. The market was once divided by canals (now closed) to reflect moonlight and remains one of India\'s largest wholesale markets.</p>`
   `   </div>`

![image](https://user-images.githubusercontent.com/47409579/103218398-e134ca80-4940-11eb-8fbc-1c5516b5b562.png)
