### ISSUE TITLE
Runtime issue: Cannot read property 'getFlattenedTree' of undefined

### ISSUE THREAD

**Issue by Anmol406** [dequelabs/axe-core#2884]
<< Please describe how you encountered this issue >> i was trying to check the Accessibility of the DEQUE page and while inspecting the element i clicked on Axe dev tools and while running the inspection the error occurred.

axe-core version: `4.1.3`
axe-extension version: `4.8.6`

```
TypeError: Cannot read property 'getFlattenedTree' of undefined
    at s (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/content.bundle.js:31:11737)
    at Object.getFlattenedTree (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/content.bundle.js:31:13752)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/content.bundle.js:33:6685
```

**Comment by WilcoFiers** [comment]
Thanks for reporting. This looks to be an extension issue. I'll forward this to the appropriate folks.

**Comment by erik-deque** [comment]
@Anmol406, are there issues missing from the scan or are you experiencing unexpected behavior with the extension?

**Comment by Anmol406** [comment]
Hi Erik,
These are unexpected issue I have ever faced while using the tool. I have
observed this simply while I was performing the scan. No scenerios were
performed. But if you want me to perform different scenarios I can do that.
For this issue these are the mentioned steps:
1) open the website
2) open dev tool section
3) tap on axe dev tool
4) tap on scan

I was not able to scan the page immediately after tapping on scan button I
observed this issue.
But now as I use the tool it is working issue, maybe there was any network
issue or any updation issue.

Thanks and regards

**Comment by erik-deque** [comment]
I've been trying to reproduce without success, is there a particular url you could share where this was more common?

**Comment by Anmol406** [comment]
Hi Erik,
Now I am not able to remember the URL maybe incase I find found the URL
I'll mail you back.

Thanks and regards,
Anmol Dhiman

**Comment by dylanb** [comment]
Closing this due to inactivity
