### ISSUE TITLE
Runtime issue: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by MikeHarris105** [dequelabs/axe-core#2928]
<< I ran axe on the whole page of a geckoboard sharing url : https://share.geckoboard.com/dashboards/ZRJLCO4PAYMCXRTW >>

axe-core version: `4.2.0`
axe-extension version: `4.9.3`

```
TypeError: Cannot read property 'data' of undefined
    at Xl._l [as after] (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:289593)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:324563
    at Array.forEach (<anonymous>)
    at ec.after (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:324396)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:332384
    at Array.map (<anonymous>)
    at e.value (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:332240)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:341091
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:97118
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:100990
```

**Comment by WilcoFiers** [comment]
@MikeHarris105 Thank you for reporting. I'll pass this along to the appropriate people.

**Comment by buckett** [comment]
We've also seen this issue when scanning an application.

**Comment by WilcoFiers** [comment]
We're working on a fix for this. Should be out soon. Thank you for your patience.

**Comment by WilcoFiers** [comment]
This issue is a duplicate. We believe this has been resolved.
