### ISSUE TITLE
Empty tab is opened and closed in browser in the analyzePost43x private method of AxeBuilder.java class

### ISSUE THREAD

**Issue by tvtester** [dequelabs/axe-core#3399]
Following method is opening empty tab in the browser at the code:  `String prevWindow = WebDriverExtensions.openAboutBlank(webDriver);` and `WebDriverExtensions.closeAboutBlank(webDriver, prevWindow);`

`private Results analyzePost43x(final WebDriver webDriver, final Object rawContextArg) {
    String rawOptionsArg = getOptions().equals("{}")
        ? AxeReporter.serialize(runOptions) : getOptions();

    ArrayList<Object> partialResults;
    try {
      partialResults = runPartialRecursive(webDriver, rawOptionsArg, rawContextArg, true);
    } catch (RuntimeException re) {
      if (re.getMessage().contains("Unable to inject axe script")) {
        throw re;
      }
      return buildErrorResults(re);
    }

    String prevWindow = WebDriverExtensions.openAboutBlank(webDriver);
    injectAxe(webDriver);
    Object resResponse;
    try {
      resResponse = WebDriverInjectorExtensions.executeScript(webDriver, finishRunScript, partialResults);
    } catch (Exception e) {
      throw new RuntimeException("axe.finishRun failed. Please check out https://github.com/dequelabs/axe-core-maven-html/blob/develop/error-handling.md", e);

    }
    WebDriverExtensions.closeAboutBlank(webDriver, prevWindow);
    Results res = objectMapper.convertValue(resResponse, Results.class);

    return res;
  }`

Product: 

Expectation: Empty or additional tab should not be open in the browser

Actual: Driver is opening empty tab and close it, though there is no need of it

Motivation: 

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by WilcoFiers** [comment]
@tvtester This is intentional. As of axe-core 4.3 a number of operations are run in an isolated context. That's what the blank frame is for. This is to improve integrity and security of the results.

Are you experiencing any difficulties because of this change? We've attempted to do this in a way that was unlikely to impact the environment, although admittedly this does have some impact on performance.

**Comment by rshidling** [comment]
With only Safari Browser I am getting the below error 

`org.openqa.selenium.NoSuchWindowException: 
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host:, os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_202'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: Safari, browserVersion: 15.0, javascriptEnabled: true, platform: MAC, platformName: MAC, safari:automaticInspection: false, safari:automaticProfiling: false, safari:diagnose: false, safari:platformBuildVersion: 20G165, safari:platformVersion: 11.6, safari:useSimulator: false, setWindowRect: true, strictFileInteractability: false, webdriver.remote.sessionid: 5423BD3E-DA04-4A24-8A59-A99..., webkit:WebRTC: {DisableICECandidateFiltering: false, DisableInsecureMediaCapture: false}}
Session ID: 5423BD3E-DA04-4A24-8A59-A99216287B4E
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.window(RemoteWebDriver.java:899)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.window(RemoteWebDriver.java:910)
	at com.deque.html.axecore.extensions.WebDriverExtensions.closeAboutBlank(WebDriverExtensions.java:148)
	at com.deque.html.axecore.selenium.AxeBuilder.analyzePost43x(AxeBuilder.java:620)
	at com.deque.html.axecore.selenium.AxeBuilder.analyzeRawContext(AxeBuilder.java:527)
	at com.deque.html.axecore.selenium.AxeBuilder.analyze(AxeBuilder.java:485)
	at globalLibrary.AccessibilityUtils.axeCore(AccessibilityUtils.java:410)
	at globalLibrary.AccessibilityUtils.testAccessibilityWithWCAGStandards(AccessibilityUtils.java:550)
	at ellucianethosexperienceLibrary.eeeCommon.accessibilityTest(eeeCommon.java:1912)
	at ellucianethosexperienceTest.eeeDashboardHomeEmbeddedUrlCard.UserSeesCorrectContentInEmbeddedUrlCard(eeeDashboardHomeEmbeddedUrlCard.java:139)
	at com.eee.testcases.eeeDashboardHomeEmbeddedUrlCard_Test.UserSeesCorrectContentInEmbeddedUrlCard(eeeDashboardHomeEmbeddedUrlCard_Test.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:240)
	at com.test.globaldriver.Testbase.run(Testbase.java:3280)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:252)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:593)
	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
`

**Comment by straker** [comment]
@rshidling Interesting. Does the error happen on a specific url, or does the error always happen for any url? If it's a specific url, are you able to share the url?

**Comment by sriramkukkadapu** [comment]
I am facing this same issue. @straker 

PFA code. I am using selenium latest version ad axe dependency also latest version.

Code:
===========

package Accessibility_AXECore;
import java.io.IOException;
import javax.naming.OperationNotSupportedException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import com.deque.html.axecore.extensions.WebDriverExtensions;
import com.deque.html.axecore.results.Results;
import com.deque.html.axecore.selenium.AxeBuilder;
public class ChromeTestAccessibility {
    public static void main(String args[]) throws OperationNotSupportedException, IOException {
        WebDriver driver = new ChromeDriver();
        driver.get("https://www.google.co.in");
//        Results results = WebDriverExtensions.analyze(driver);
        Results results = new AxeBuilder().analyze(driver);
        System.out.println(results.toString());
        driver.quit();
    }
}


Error i am facing:
=================
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Starting ChromeDriver 2.40.565386 (45a059dc425e08165f9a10324bd1380cc13ca363) on port 15441
Only local connections are allowed.
Feb 26, 2023 1:25:28 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 110, so returning the closest version found: 109
Exception in thread "main" java.lang.NullPointerException
	at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:423)
	at com.deque.html.axecore.extensions.WebDriverExtensions.closeAboutBlank(WebDriverExtensions.java:146)
	at com.deque.html.axecore.selenium.AxeBuilder.analyzePost43x(AxeBuilder.java:610)
	at com.deque.html.axecore.selenium.AxeBuilder.analyzeRawContext(AxeBuilder.java:505)
	at com.deque.html.axecore.selenium.AxeBuilder.analyze(AxeBuilder.java:463)
	at Accessibility_AXECore.ChromeTestAccessibility.main(ChromeTestAccessibility.java:24)
	
	
Maven dependencies that i have
===========================
		<dependency>
		    <groupId>com.deque.html.axe-core</groupId>
		    <artifactId>selenium</artifactId>
		    <version>4.5.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
				<version>4.8.0</version> 
		</dependency>
		
		
		<dependency>
		    <groupId>org.seleniumhq.selenium</groupId>
		    <artifactId>selenium-devtools-v108</artifactId>
		    <version>4.8.0</version>
		</dependency>

**Comment by pankaj-sukale** [comment]
Do we have any update on this ? Are we planning any fix ?

**Comment by benken-parasoft** [comment]
I occasionally run into the same NoSuchWindowException when testing on Safari.  It seems rather sporadic.

**Comment by straker** [comment]
@pankaj-sukale @benken-parasoft are both of you also experiencing this using `axe-core-maven`? If so I may move this issue to that repository for better tracking.

**Comment by benken-parasoft** [comment]
I am using the "com.deque.html.axe-core:selenium" Maven Java library.
I have been working around this issue by catching the ```NoSuchWindowException``` and trying again:
```java
import org.openqa.selenium.WebDriver;
import com.deque.html.axecore.results.Results;
import com.deque.html.axecore.selenium.AxeBuilder;
...
    static Results analyze(AxeBuilder builder, WebDriver webDriver) {
        try {
            return builder.analyze(webDriver);
        } catch (NoSuchWindowException e) {
            // retry if NoSuchWindowException is thrown
            // see issue https://github.com/dequelabs/axe-core/issues/3399#issuecomment-1081653088
            return builder.analyze(webDriver);
        }
    }
```

I only run into this issue on Safari on macOS.  The NoSuchWindowException happens a bit randomly.

**Comment by straker** [comment]
Thanks for the info. I'm going to port this issue to axe-core-maven repository as it looks like it's  a Java issue, and more specifically could be a Safari and MacOs issue.
