### ISSUE TITLE
Runtime issue: Cannot read properties of undefined (reading 'source')

### ISSUE THREAD

**Issue by samicaustin** [dequelabs/axe-core#3504]
<< Please describe how you encountered this issue >>

axe-core version: `4.4.2`
axe-extension version: `4.29.0`

```
TypeError: Cannot read properties of undefined (reading 'source')
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167249
    at Array.map (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167219
    at Array.forEach (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167169
    at Array.forEach (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167065
    at Array.map (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:166733
    at Array.map (<anonymous>)
```

**Comment by straker** [comment]
Thanks for the issue. Does this only happen in your dev environment, or does it also happen in the prod environment?
