### ISSUE TITLE
Runtime issue: No elements found for include in page Context

### ISSUE THREAD

**Issue by hacaothanh** [dequelabs/axe-core#3642]
<< Please describe how you encountered this issue >>

axe-core version: `4.4.2`
axe-extension version: `4.36.2`

```
Error: No elements found for include in page Context
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:172417
    at new jn (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:172608)
    at Object.M1 [as _runRules] (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:350025)
    at axe.run (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:356602)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/content.bundle.js:1:12390
```

**Comment by WilcoFiers** [comment]
Can you provide some information on how to reproduce this issue?

**Comment by straker** [comment]
Closing due to inactivity. Feel free to reopen if this is still a problem and can provide information on how to reporduce.
