### ISSUE TITLE
Runtime issue: n[e].push is not a function

### ISSUE THREAD

**Issue by ctcpip** [dequelabs/axe-core#4000]
using the chrome extension, when running the scan on `https://tc39.es/ecma262/`

axe-core version: `4.6.3`
axe-extension version: `4.55.0`

```
TypeError: n[e].push is not a function
    at _i (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:220066)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:220246
    at Array.forEach (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:220225
    at Array.forEach (<anonymous>)
    at Si (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:220163)
    at Ii (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:220320)
    at Pi (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:221091)
    at i (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:220420)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:221170
```

**Comment by WilcoFiers** [comment]
Thanks for reporting! That's a surprising one. Turns out axe-core doesn't like it when you have `id="constructor"` on an element. We can fix that.
