### ISSUE TITLE
Runtime issue: Axe is already running. Use `await axe.run()` to wait for the previous run to finish before starting a new run.

### ISSUE THREAD

**Issue by oarogersiii** [dequelabs/axe-core#4153]
<< Please describe how you encountered this issue >>

axe-core version: `4.7.2`
axe-extension version: `4.62.0`

```
Error: Axe is already running. Use `await axe.run()` to wait for the previous run to finish before starting a new run.
    at Fn (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:72073)
    at o.run (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:452218)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/content.bundle.js:2:15461
```

**Comment by straker** [comment]
Thanks for the issue. Could you provide more details on how you encountered the issue, possibly the site (if it's public)?

**Comment by straker** [comment]
Closing due to lack of activity. Please feel free to reopen if you can provide more information.
