### ISSUE TITLE
Runtime issue: Axe in frame timed out: #twitter-widget-0

### ISSUE THREAD

**Issue by b0036327** [dequelabs/axe-core#4236]
Error: Axe in frame timed out: #twitter-widget-0
    at Xa (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:100361)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:100186

**Comment by straker** [comment]
Thanks for the issue. Could you provide some more details please, like what URL the error occurred on, the steps to reproduce the error, and which versions of the extension you're using?

**Comment by straker** [comment]
Closing due to inactivity. Feel free to reopen if you believe this is still an issue.
