### ISSUE TITLE
axecore error Cannot read properties of undefined

### ISSUE THREAD

**Issue by rajsite** [dequelabs/axe-core#4335]
### Product

axe-core

### Product Version

4.8.4

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation

I expect axe-core to be able to run without error on pages that include a shadow root such as the following:
https://axecore-lighthouse-failure.glitch.me/

#### Actual

Notice in the console of the above page that axe-core runs with a result of incomplete.
The incomplete item has:

description:
`"Ensures role attribute has an appropriate value for the element"`

error stack:
```
TypeError: Cannot read properties of undefined (reading 'props')
    at prepareContext (https://unpkg.com/axe-core@4.8.4/axe.js:12625:23)
    at _accessibleTextVirtual (https://unpkg.com/axe-core@4.8.4/axe.js:12573:17)
    at accessibleText (https://unpkg.com/axe-core@4.8.4/axe.js:9588:14)
    at https://unpkg.com/axe-core@4.8.4/axe.js:9604:33
    at Array.reduce (<anonymous>)
    at arialabelledbyText (https://unpkg.com/axe-core@4.8.4/axe.js:9603:19)
    at hasAccessibleName (https://unpkg.com/axe-core@4.8.4/axe.js:11698:45)
    at section (https://unpkg.com/axe-core@4.8.4/axe.js:11799:16)
    at implicitRole2 (https://unpkg.com/axe-core@4.8.4/axe.js:11992:16)
    at getElementUnallowedRoles (https://unpkg.com/axe-core@4.8.4/axe.js:19359:27)
```

impact: 
`null`

#### How to Reproduce

See above, example page and discussion to view the axe-core result in the console. Page url preproduced as follows: https://axecore-lighthouse-failure.glitch.me/

#### Additional context
Any thing else we should know about the issue?

**Comment by straker** [comment]
Thanks for the issue. I took a quick look at it appears that the issue is the `aria-labelledby` on the `section` element which points to the `slot` element. The `slot` element isn't tracked in our virtual tree so that's why the code is failing.

**Comment by straker** [comment]
This may have been fixed with our move to use `getAccessibleRefs` for looking up accessible name idrefs. Just need to confirm if this is still the case or not using the following code. If it's been fix then we should add an integration test as a regression test:

```html
<div>
  <template shadowrootmode="open">
    <section aria-labelledby="foo"></section>
    <slot id="foo">
  </template>
  Hello
</div>
```

In axe-core 4.11.1 this throws the error when calling `axe.commons.text.accessibleText` on the `<section>` element, or when running `axe.run` gives a few incomplete rule results with the error message.
