### ISSUE TITLE
Runtime issue: Axe in frame timed out: .U73P_q[allowtransparency="true"][allowvr="true"]

### ISSUE THREAD

**Issue by detzko** [dequelabs/axe-core#4504]
<< Please describe how you encountered this issue >>

axe-core version: `4.9.1`
axe-extension version: `4.81.4`

```
Error: Axe in frame timed out: .U73P_q[allowtransparency="true"][allowvr="true"]
    at Qo (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:112375)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:112200
```

**Comment by straker** [comment]
Thanks for the issue. Can you provide the URL that you encountered the issue on, or if not the URL a reproducible test case or description that would help us understand what happened?

**Comment by straker** [comment]
Closing due to inactivity. Feel free to reopen if you believe this is still an issue.
