### ISSUE TITLE
Runtime issue: Result for unknown rule. You may be running mismatch axe-core versions

### ISSUE THREAD

**Issue by QualityEnablement** [dequelabs/axe-core#4538]
<< Please describe how you encountered this issue >>

axe-core version: `4.9.1`
axe-extension version: `4.82.0`

```
Error: Result for unknown rule. You may be running mismatch axe-core versions
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:473463
    at Array.map (<anonymous>)
    at e.value (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:473393)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:478373
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:106157
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:115750
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:106157
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:115682
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:112319
    at post (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/content.bundle.js:2:22522)
```

**Comment by straker** [comment]
Thanks for the issue. Could you provide more details about how and where you encountered the error, or possibly a code sample that reproduces it?

I will say that most commonly when I see the "Result for unknown rule" error it happens due to a JavaScript file that overrides native JS features, mainly things like JSON.stringify / parse. You may try looking to see if the site loads any 3rd party scripts, for example http://prototypejs.org/, that would change native JS features.

**Comment by straker** [comment]
Closing due to inactivity. Feel free to reopen if you believe this is still an issue.
