### ISSUE TITLE
Runtime issue: Result for unknown rule. You may be running mismatch axe-core versions

### ISSUE THREAD

**Issue by praneetha-ck-ps** [dequelabs/axe-core#4640]
<< Please describe how you encountered this issue >>

axe-core version: `4.10.2`
axe-extension version: `4.96.1`

```
Error: Result for unknown rule. You may be running mismatch axe-core versions
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:471080
    at Array.map (<anonymous>)
    at e.value (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:471010)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:476036
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:103752
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:470814
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:103752
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:474471
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:462678
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:103752
```

**Comment by WilcoFiers** [comment]
@praneetha-ck-ps Can you provide steps to reproduce this issue?
