### ISSUE TITLE
postinstall script fails on node4

### ISSUE THREAD

**Issue by ahmadnassri** [dequelabs/axe-core#541]
```
Exit code: 1
Command: node build/utils/postinstall.js
Arguments: 
Directory: /home/ahmad/Projects/ahmadnassri/nightwatch-accessibility/node_modules/axe-core
Output:
/home/ahmad/Projects/ahmadnassri/nightwatch-accessibility/node_modules/axe-core/build/utils/postinstall.js:4
	let commitMsg = '.git/hooks/commit-msg'
	^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by brokenmass** [comment]
Can you release this as a 2.x.x version asap please ?

**Comment by brokenmass** [comment]
Bump

**Comment by marcysutton** [comment]
this was released as part of axe-core@2.4.2

**Comment by nemanjacosovic** [comment]
@marcysutton I'm having this failed on:
```
node v4.4.7
npm  v3.10.6

```
But its working on
```
node v6.10.0
npm v5.6.0
```

**Comment by marcysutton** [comment]
axe-core requires node 6.
