### ISSUE TITLE
Failed to execute querySelectorAll

### ISSUE THREAD

**Issue by patrickhulce** [dequelabs/axe-core#599]
Hey folks first sayin' a big thank you for your great work :)

We discovered this over in Lighthouse on https://www.walgreens.com/store/c/contact-lenses/ID=359432-tier2clense?vredirID=1

Trying in the extension does nothing after clicking "Analyze" and throwing axe into the page running manually yields the error below which is the same as what you get with Lighthouse. Seems like you might need to [escape the colon](https://stackoverflow.com/questions/20468571/get-a-custom-tag-containing-colon-value-using-jquery) in the custom tag name?

Anecdotally, I also saw this happen to another Lighthouse user at Chrome Dev Summit so it isn't isolated to just this page.

```
DOMException: Failed to execute 'querySelectorAll' on 'Document': 'wag:view-product-details' is not a valid selector.
    at HTMLDocument.querySelectorAll (https://www.walgreens.com/i10c@p1/client/nv-8.0.6/auto/instart.js?i10c.opts=monitor.html_streaming:73:185)
    at createUniqueSelector (https://cdnjs.cloudflare.com/ajax/libs/axe-core/2.4.2/axe.js:2058:47)
    at createUniqueSelector (https://cdnjs.cloudflare.com/ajax/libs/axe-core/2.4.2/axe.js:2066:14)
    at createUniqueSelector (https://cdnjs.cloudflare.com/ajax/libs/axe-core/2.4.2/axe.js:2066:14)
    at createUniqueSelector (https://cdnjs.cloudflare.com/ajax/libs/axe-core/2.4.2/axe.js:2066:14)
    at createUniqueSelector (https://cdnjs.cloudflare.com/ajax/libs/axe-core/2.4.2/axe.js:2066:14)
    at createUniqueSelector (https://cdnjs.cloudflare.com/ajax/libs/axe-core/2.4.2/axe.js:2066:14)
    at createUniqueSelector (https://cdnjs.cloudflare.com/ajax/libs/axe-core/2.4.2/axe.js:2066:14)
    at createUniqueSelector (https://cdnjs.cloudflare.com/ajax/libs/axe-core/2.4.2/axe.js:2066:14)
    at Object.createUniqueSelector [as getSelector] (https://cdnjs.cloudflare.com/ajax/libs/axe-core/2.4.2/axe.js:2066:14)
```

**Comment by dylanb** [comment]
Looks like whenever we receive a selector that has a special character like `:`, we should escape it `\\:`

**Comment by marcysutton** [comment]
I think this should already be covered by #566, possibly. It's choking on the invalid tag name.

**Comment by patrickhulce** [comment]
Ah yeah looks like a dupe of #563!

**Comment by marcysutton** [comment]
Ok, I'll close this as a duplicate. Thanks for your report!
