### ISSUE TITLE
axe.utils.querySelectorAll doesn't support prefix (startsWith) attribute selector

### ISSUE THREAD

**Issue by marcysutton** [dequelabs/axe-core#727]
When trying to convert `internal-link-present` to support Shadow DOM, I found the querySelectorAll util for aXe 3 doesn't support `'a[href^="#"]'`.

Here's the code in the check:
```
return !!node.querySelector('a[href^="#"]');
```
Here's the code I tried to use when converting:
```
return !!axe.utils.querySelectorAll(virtualNode, 'a[href^="#"]')[0];
```
I get the following error: 
```
Error: Expected "=" but "^" found.
    at ParseContext.parseRule (http://localhost:9876/axe.js:2021:23)
    at ParseContext.parseSingleSelector (http://localhost:9876/axe.js:1953:25)
    at ParseContext.parseSelector (http://localhost:9876/axe.js:1929:35)
    at ParseContext.parse (http://localhost:9876/axe.js:1921:24)
    at CssSelectorParser.parse (http://localhost:9876/axe.js:2116:22)
    at Object.axe.utils.querySelectorAllFilter (http://localhost:9876/axe.js:3598:43)
    at Object.axe.utils.querySelectorAll (http://localhost:9876/axe.js:3594:22)
    at Object.evaluate (http://localhost:9876/tmp/rules.js:1846:23)
    at Context.<anonymous> (navigation/internal-link-present.js:18:58)
```

**Comment by WilcoFiers** [comment]
You should be able to do this:
```js
const links = axe.utils.querySelectorAll(virtualNode, 'a[href]');
return links.some(link => link.getAttribute('href')[0] === '#');
```

**Comment by marcysutton** [comment]
Should we close this since I was able to accomplish it another way? I don't want to add unnecessary work to our plates.
