### ISSUE TITLE
Runtime issue: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by kkilton** [dequelabs/axe-core#996]
Ran analyzer against an Angular 5 local website. This code is breaking it. Where CIIS_Approval has some strong tags, br tags, p tagss. I change the outer 'span' to a 'p' and it runs fine.
`<span id="CIIS_Approval" [innerHtml]="'CIIS_Approval' | translate"></span><i fa class="fa fa-asterisk fa-required"></i>`

```
TypeError: Cannot read property '0' of undefined
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-adapter.js:46958:39
    at Array.every (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-adapter.js:46957:28
    at Array.forEach (<anonymous>)
    at Object.color.filteredRectStack (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-adapter.js:46951:21)
    at Object.color.getBackgroundStack (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-adapter.js:46972:30)
    at Object.color.getBackgroundColor (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-adapter.js:46994:30)
    at Object.evaluate (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-adapter.js:43950:41)
    at Check../node_modules/axe-core/axe.js.Check.run (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-adapter.js:37303:32)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-adapter.js:37559:15
```

**Comment by marcysutton** [comment]
We need a live demo to debug further, can you provide something for us that includes the rendered page?

**Comment by marcysutton** [comment]
@kkilton is Angular really rendering square brackets around an attribute in the final compiled source? That would break a lot of things, not just axe. 

A reminder that we need more actionable details in this issue to reproduce the problem, otherwise it will be closed due to inactivity. Thanks!
